spring:
  application:
    name: t1aop
  datasource:
    url: jdbc:postgresql://localhost:5432/aop
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
